# This Dockerfile is used to create the image for the TF Serving application
FROM tensorflow/serving

ENV APP_HOME /saved_models/1628956907
WORKDIR $APP_HOME

COPY ./saved_models /saved_models/1628956907